[mgr]  
prepend_keymap = [  
  { on = "-", run = "leave", desc = "親ディレクトリへ移動" },
  { on = "<Enter>", run = "plugin smart-enter" },
  { on = "p", run = "plugin smart-paste" },
  { on = "<Space>", run = "plugin bunny" },
  { on = "~", run = "cd ~", desc = "ホームディレクトリへ移動" },
  { on = "z", run = "plugin zoxide", desc = "zoxide" },
  { on = "o", run = "create" },
  { on = "<C-o>", run = "back" },
  { on = "<C-i>", run = "forward" },
  { on = ["g", "?"], run = "help" },
  { on = "<C-p>", run = "plugin toggle-pane max-preview" },
  { on = "_", run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"' }
]

[input]  
prepend_keymap = [  
  { on = "<Esc>", run = "close", desc = "Cancel input" }
]

