[mgr]  
prepend_keymap = [  
  { on = "-", run = "leave", desc = "親ディレクトリへ移動" },
  { on = ["i", "<Space>"], run = "cd --interactive", desc = "パスを入力してcd" },
  { on = "<Enter>", run = "plugin smart-enter" },
  { on = "p", run = "plugin smart-paste" },
  { on = "e", run = "plugin bunny" },
  { on = "z", run = "plugin zoxide", desc = "zoxide" },
  { on = "o", run = "create" },
  { on = "f", run = "search" },
  { on = "<C-o>", run = "back" },
  { on = "<C-i>", run = "forward" },
  { on = ["g", "?"], run = "help" },
  { on = "<C-p>", run = "plugin toggle-pane max-preview" },
  { on = "<C-y>", run = "plugin system-clipboard" },
  { on = ["<Space>", "g"], run = "shell --block -- lazygit" },
  { on = ["g", "r"], run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"' }
]

[input]  
prepend_keymap = [  
  { on = "<Esc>", run = "close", desc = "Cancel input" }
]
