[mgr]
show_hidden = true
linemode = "mtime"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"

[preview]
max_width  = 3600
max_height = 2338

[opener]  
preview = [
  { run = 'qlmanage -p "$1"', desc = "Quick Look Preview"}
]
gimp = [  
  { run = 'LANG=ja gimp -n "$1"', desc = "GIMP"}
]

[open]  
prepend_rules = [
  { mime = "image/*", use = ["preview", "open", "reveal", "gimp"] },
  { mime = "video/webm", use = "open" },
]
